export const en = {
  // General
  appName: 'Workers Welfare Board',
  govt: 'Government of Punjab',
  language: 'Language',
  english: 'English',
  urdu: 'اردو',
  loading: 'Loading...',
  error: 'Error',
  retry: 'Try Again',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  next: 'Next',
  back: 'Back',
  submit: 'Submit',
  edit: 'Edit',

  // Auth
  login: 'Sign In',
  register: 'Register',
  phoneNumber: 'Phone Number',
  phoneHint: 'Enter the number registered with your CNIC',
  sendOtp: 'Send OTP',
  otpSent: 'OTP Sent',
  enterOtp: 'Enter OTP',
  otpHint: 'A 6-digit code was sent to your phone',
  verifyOtp: 'Verify OTP',
  otpExpiry: 'OTP expires in 5 minutes',
  registerInstead: 'Register as new worker?',
  loginInstead: 'Already have an account?',
  authorisedOnly: 'Authorised Personnel Only',

  // Registration
  cnic: 'CNIC Number',
  cnicHint: '00000-0000000-0',
  cnicChecking: 'Verifying with NADRA...',
  cnicVerified: 'CNIC Verified',
  cnicFailed: 'CNIC Verification Failed',
  nameFromNadra: 'Name (from NADRA)',
  step1: 'Step 1: Identity',
  step2: 'Step 2: Employment Details',
  step3: 'Step 3: Phone Verification',
  step4: 'Step 4: Confirmation',
  employer: 'Employer / Establishment',
  jobTitle: 'Job Title / Designation',
  joiningDate: 'Date of Joining',
  payScale: 'Monthly Pay Scale (PKR)',
  address: 'Address',
  paymentMode: 'Payment Mode',
  bankTransfer: 'Bank Transfer',
  cash: 'Cash',
  bankName: 'Bank Name',
  bankAccount: 'Bank Account Number',
  eobiNumber: 'EOBI Number',
  ssNumber: 'Social Security Number',
  registrationSuccess: 'Registration Complete',
  registrationSuccessMsg: 'Your application has been submitted for multi-department verification.',

  // Dashboard
  myProfile: 'My Profile',
  verificationStatus: 'Verification Status',
  deptVerified: 'Departments Verified',
  of: 'of',

  // Departments
  labourDept: 'Labour Dept',
  police: 'Police',
  eobi: 'EOBI',
  socialSecurity: 'Social Security',
  fbr: 'FBR',
  excise: 'Excise & Taxation',
  civilDefense: 'Civil Defense',
  districtAdmin: 'District Admin',

  // Status
  verified: 'Verified',
  pending: 'Pending',
  flagged: 'Flagged',
  rejected: 'Rejected',

  // Profile
  fullName: 'Full Name',
  fatherName: "Father / Husband's Name",
  dob: 'Date of Birth',
  gender: 'Gender',
  district: 'District',
  phone: 'Phone',
  wwbRegNo: 'WWB Registration No.',

  // Documents
  myCard: 'My Registration Card',
  shareCard: 'Share Card',
  lastSynced: 'Last synced',
  offline: 'Offline',
  offlineMsg: 'No internet connection available',
};
