export const ur = {
  // General
  appName: 'ورکرز ویلفیئر بورڈ',
  govt: 'حکومتِ پنجاب',
  language: 'زبان',
  english: 'English',
  urdu: 'اردو',
  loading: 'لوڈ ہو رہا ہے...',
  error: 'خرابی',
  retry: 'دوبارہ کوشش کریں',
  save: 'محفوظ کریں',
  cancel: 'منسوخ کریں',
  confirm: 'تصدیق',
  next: 'آگے',
  back: 'واپس',
  submit: 'جمع کریں',
  edit: 'ترمیم',

  // Auth
  login: 'لاگ ان',
  register: 'رجسٹریشن',
  phoneNumber: 'فون نمبر',
  phoneHint: 'اپنا وہ نمبر لکھیں جو CNIC میں ہے',
  sendOtp: 'OTP بھیجیں',
  otpSent: 'OTP بھیجا جا چکا ہے',
  enterOtp: 'OTP درج کریں',
  otpHint: 'آپ کے فون پر 6 ہندسوں کا کوڈ بھیجا گیا ہے',
  verifyOtp: 'OTP تصدیق کریں',
  otpExpiry: 'OTP 5 منٹ میں ختم ہو جائے گا',
  registerInstead: 'نئی رجسٹریشن کریں؟',
  loginInstead: 'پہلے سے اکاؤنٹ ہے؟',
  authorisedOnly: 'صرف اجازت یافتہ افراد',

  // Registration
  cnic: 'شناختی کارڈ نمبر',
  cnicHint: '00000-0000000-0',
  cnicChecking: 'NADRA سے تصدیق ہو رہی ہے...',
  cnicVerified: 'شناختی کارڈ تصدیق شدہ',
  cnicFailed: 'شناختی کارڈ تصدیق ناکام',
  nameFromNadra: 'NADRA سے نام',
  step1: 'مرحلہ ۱: شناختی کارڈ',
  step2: 'مرحلہ ۲: ملازمت کی تفصیل',
  step3: 'مرحلہ ۳: فون تصدیق',
  step4: 'مرحلہ ۴: تصدیق',
  employer: 'آجر / کمپنی',
  jobTitle: 'عہدہ',
  joiningDate: 'ملازمت کی تاریخ',
  payScale: 'ماہانہ تنخواہ (روپے)',
  address: 'پتہ',
  paymentMode: 'ادائیگی کا طریقہ',
  bankTransfer: 'بینک ٹرانسفر',
  cash: 'نقد',
  bankName: 'بینک کا نام',
  bankAccount: 'بینک اکاؤنٹ نمبر',
  eobiNumber: 'EOBI نمبر',
  ssNumber: 'سوشل سیکیورٹی نمبر',
  registrationSuccess: 'رجسٹریشن مکمل',
  registrationSuccessMsg: 'آپ کی درخواست محکموں کو تصدیق کے لیے بھیج دی گئی ہے',

  // Dashboard
  myProfile: 'میری پروفائل',
  verificationStatus: 'تصدیقی حیثیت',
  deptVerified: 'تصدیق شدہ محکمے',
  of: 'میں سے',

  // Departments
  labourDept: 'محکمہ محنت',
  police: 'پولیس',
  eobi: 'EOBI',
  socialSecurity: 'سوشل سیکیورٹی',
  fbr: 'FBR',
  excise: 'محکمہ ایکسائز',
  civilDefense: 'سول ڈیفنس',
  districtAdmin: 'ضلعی انتظامیہ',

  // Status
  verified: 'تصدیق شدہ',
  pending: 'زیرِ التواء',
  flagged: 'مشکوک',
  rejected: 'مسترد',

  // Profile
  fullName: 'پورا نام',
  fatherName: 'والد / شوہر کا نام',
  dob: 'تاریخ پیدائش',
  gender: 'جنس',
  district: 'ضلع',
  phone: 'فون',
  wwbRegNo: 'WWB رجسٹریشن نمبر',

  // Documents
  myCard: 'میرا شناختی کارڈ',
  shareCard: 'کارڈ شیئر کریں',
  lastSynced: 'آخری بار مطابقت',
  offline: 'آف لائن',
  offlineMsg: 'انٹرنیٹ کنیکشن دستیاب نہیں',
};
